name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-12, macos-11, macos-10.15, ubuntu-20.04, ubuntu-18.04, windows-2022, windows-2019]
  
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - run: make noomp -j
      env:
        CXXFLAGS: -Werror -Wno-unknown-pragmas
    - run: ./Infomap --version
