name: Build JavaScript Worker

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: mymindstorm/setup-emsdk@v9
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: make -j js-worker
